setx MOIEN_DATABASE_HOST "db.ehsqsjahchtbbvuxgiqr.supabase.co"
setx MOIEN_DATABASE_PASSWORD "HKp6GuYZT40t1HtH2E5JN6JI5JYZ8iaH"
setx MOIEN_DATABASE_URL "https://ehsqsjahchtbbvuxgiqr.supabase.co"
setx MOIEN_DATABASE_KEY "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoc3FzamFoY2h0YmJ2dXhnaXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDk1NjQ5MTksImV4cCI6MjAyNTE0MDkxOX0.bZM56LCFwxaT2Q1l7iXna5a4ZdsxOYJ8AtP0WZYTrmc"
setx MOIEN_STORAGE_URL "https://ehsqsjahchtbbvuxgiqr.supabase.co/storage/v1/object/public"
pause
